import type {
  Client, Employee, Timesheet, AIInsight, PayrollSummary,
  Portal, PolicyRule, PayrollBatch,
} from "./types"

// ─── Portals (10) ─────────────────────────────────────────────────────────────

export const portals: Portal[] = [
  {
    id: "veltrix",
    name: "Veltrix HCM",
    shortName: "Veltrix",
    tagline: "Velocity-driven HR lifecycle management",
    color: "#FF6B35",
    bgColor: "rgba(255,107,53,0.08)",
    status: "connected",
    connectedClientIds: ["hex", "wvl", "psy"],
    totalEmployees: 19800,
    lastSyncAt: "2026-04-10T07:45:00Z",
    nextSyncAt: "2026-04-10T08:00:00Z",
    syncFrequency: "15min",
    totalSyncedThisMonth: 1840,
    pendingInQueue: 12,
    errorCount: 0,
    apiVersion: "v3.1",
    webhookEnabled: true,
    features: ["Real-time webhooks", "Bulk export", "Leave sync", "Shift roster", "Payslip push"],
    authMethod: "oauth2",
    tier: "enterprise",
    successRate: 99.4,
    avgSyncMs: 320,
  },
  {
    id: "hrloop",
    name: "HRLoop",
    shortName: "HRLoop",
    tagline: "Closed-loop HR & payroll automation",
    color: "#00A86B",
    bgColor: "rgba(0,168,107,0.08)",
    status: "connected",
    connectedClientIds: ["gss", "tes", "kpt"],
    totalEmployees: 6300,
    lastSyncAt: "2026-04-10T07:30:00Z",
    nextSyncAt: "2026-04-10T08:30:00Z",
    syncFrequency: "1hr",
    totalSyncedThisMonth: 610,
    pendingInQueue: 4,
    errorCount: 1,
    apiVersion: "v2.4",
    webhookEnabled: true,
    features: ["Auto-sync", "Leave integration", "Attendance import", "ESS portal"],
    authMethod: "api_key",
    tier: "business",
    successRate: 98.7,
    avgSyncMs: 480,
  },
  {
    id: "peoplehive",
    name: "PeopleHive",
    shortName: "PeopleHive",
    tagline: "Where teams grow together",
    color: "#7B68EE",
    bgColor: "rgba(123,104,238,0.08)",
    status: "connected",
    connectedClientIds: ["tci", "hhc", "zns"],
    totalEmployees: 7200,
    lastSyncAt: "2026-04-10T07:15:00Z",
    nextSyncAt: "2026-04-10T08:15:00Z",
    syncFrequency: "1hr",
    totalSyncedThisMonth: 720,
    pendingInQueue: 7,
    errorCount: 0,
    apiVersion: "v1.9",
    webhookEnabled: true,
    features: ["Smart timesheet", "Leave management", "Geo attendance", "Performance link"],
    authMethod: "oauth2",
    tier: "business",
    successRate: 99.1,
    avgSyncMs: 410,
  },
  {
    id: "orbithcm",
    name: "OrbitHCM",
    shortName: "OrbitHCM",
    tagline: "Enterprise-grade workforce management in orbit",
    color: "#0070F3",
    bgColor: "rgba(0,112,243,0.08)",
    status: "connected",
    connectedClientIds: ["ibp", "cdg", "mnd"],
    totalEmployees: 29600,
    lastSyncAt: "2026-04-10T07:00:00Z",
    nextSyncAt: "2026-04-10T11:00:00Z",
    syncFrequency: "4hr",
    totalSyncedThisMonth: 2900,
    pendingInQueue: 24,
    errorCount: 2,
    apiVersion: "v4.0",
    webhookEnabled: false,
    features: ["OData API", "Workforce analytics", "Global compliance", "EC integration"],
    authMethod: "saml",
    tier: "enterprise",
    successRate: 97.8,
    avgSyncMs: 1240,
  },
  {
    id: "cloudspire",
    name: "CloudSpire",
    shortName: "CloudSpire",
    tagline: "Cloud-native HCM built for enterprise scale",
    color: "#F5A623",
    bgColor: "rgba(245,166,35,0.08)",
    status: "connected",
    connectedClientIds: ["cgi", "lti"],
    totalEmployees: 17700,
    lastSyncAt: "2026-04-10T04:00:00Z",
    nextSyncAt: "2026-04-11T04:00:00Z",
    syncFrequency: "24hr",
    totalSyncedThisMonth: 1680,
    pendingInQueue: 30,
    errorCount: 0,
    apiVersion: "v38.2",
    webhookEnabled: false,
    features: ["SOAP/REST API", "Calculated fields", "Business process", "Reporting cloud"],
    authMethod: "oauth2",
    tier: "enterprise",
    successRate: 99.8,
    avgSyncMs: 1820,
  },
  {
    id: "leafhr",
    name: "LeafHR",
    shortName: "LeafHR",
    tagline: "Grow your people, naturally",
    color: "#73C41D",
    bgColor: "rgba(115,196,29,0.08)",
    status: "connected",
    connectedClientIds: ["mpc", "idn"],
    totalEmployees: 5650,
    lastSyncAt: "2026-04-10T06:00:00Z",
    nextSyncAt: "2026-04-10T10:00:00Z",
    syncFrequency: "4hr",
    totalSyncedThisMonth: 540,
    pendingInQueue: 3,
    errorCount: 0,
    apiVersion: "v1.0",
    webhookEnabled: true,
    features: ["Webhooks", "Open API", "eSignature", "Onboarding flows"],
    authMethod: "api_key",
    tier: "business",
    successRate: 99.3,
    avgSyncMs: 280,
  },
  {
    id: "humanedge",
    name: "HumanEdge",
    shortName: "HumanEdge",
    tagline: "People-powered productivity platform",
    color: "#E42527",
    bgColor: "rgba(228,37,39,0.08)",
    status: "connected",
    connectedClientIds: ["fhl", "mtd"],
    totalEmployees: 1420,
    lastSyncAt: "2026-04-10T07:00:00Z",
    nextSyncAt: "2026-04-10T08:00:00Z",
    syncFrequency: "1hr",
    totalSyncedThisMonth: 140,
    pendingInQueue: 2,
    errorCount: 3,
    apiVersion: "v2",
    webhookEnabled: true,
    features: ["REST API", "Biometric sync", "Leave automation", "Shift scheduling"],
    authMethod: "oauth2",
    tier: "starter",
    successRate: 96.2,
    avgSyncMs: 390,
  },
  {
    id: "payaxis",
    name: "PayAxis",
    shortName: "PayAxis",
    tagline: "Axis-point for payroll & workforce compliance",
    color: "#D40000",
    bgColor: "rgba(212,0,0,0.08)",
    status: "connected",
    connectedClientIds: ["brl"],
    totalEmployees: 1650,
    lastSyncAt: "2026-04-10T05:00:00Z",
    nextSyncAt: "2026-04-11T05:00:00Z",
    syncFrequency: "24hr",
    totalSyncedThisMonth: 160,
    pendingInQueue: 1,
    errorCount: 0,
    apiVersion: "v2.0",
    webhookEnabled: false,
    features: ["Open Marketplace API", "Tax compliance", "Direct deposit", "Labor analytics"],
    authMethod: "oauth2",
    tier: "enterprise",
    successRate: 99.6,
    avgSyncMs: 950,
  },
  {
    id: "talentweave",
    name: "TalentWeave",
    shortName: "TalentWeave",
    tagline: "AI-native HR woven for Asia-Pacific teams",
    color: "#6C3AFF",
    bgColor: "rgba(108,58,255,0.08)",
    status: "syncing",
    connectedClientIds: ["msh", "cyn"],
    totalEmployees: 4120,
    lastSyncAt: "2026-04-10T07:50:00Z",
    nextSyncAt: "2026-04-10T08:50:00Z",
    syncFrequency: "1hr",
    totalSyncedThisMonth: 400,
    pendingInQueue: 18,
    errorCount: 1,
    apiVersion: "v3.5",
    webhookEnabled: true,
    features: ["Multi-country", "Alt Workforce", "AI insights", "Compliance pack"],
    authMethod: "api_key",
    tier: "enterprise",
    successRate: 98.1,
    avgSyncMs: 560,
  },
  {
    id: "staffpulse",
    name: "StaffPulse",
    shortName: "StaffPulse",
    tagline: "Real-time pulse on your entire workforce",
    color: "#00C4B4",
    bgColor: "rgba(0,196,180,0.08)",
    status: "connected",
    connectedClientIds: ["nit", "snt", "ngs"],
    totalEmployees: 2190,
    lastSyncAt: "2026-04-10T07:00:00Z",
    nextSyncAt: "2026-04-10T08:00:00Z",
    syncFrequency: "1hr",
    totalSyncedThisMonth: 210,
    pendingInQueue: 5,
    errorCount: 0,
    apiVersion: "v1.3",
    webhookEnabled: true,
    features: ["Open REST API", "Attendance module", "Expense management", "Mobile app sync"],
    authMethod: "api_key",
    tier: "business",
    successRate: 98.9,
    avgSyncMs: 310,
  },
]

// ─── Clients (25) ─────────────────────────────────────────────────────────────

export const clients: Client[] = [
  // ─ Large Enterprise (>5k employees) ────────────────────────────────────────
  { id:"hex", name:"Hexaware Technologies",   code:"HEX", color:"#FF6B35", industry:"IT Services",  city:"Mumbai",     state:"Maharashtra",  employeeCount:12500, activeEmployeeCount:11800, portalId:"veltrix",   portalName:"Veltrix HCM",    policyVersion:"v4.2", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2022-04-01", contractEnd:"2027-03-31", accountManager:"Priya Shah",     billingCurrency:"INR", status:"active", monthlyPayroll:31200000, pendingTimesheets:87, complianceScore:94 },
  { id:"ibp", name:"Infosys BPM",             code:"IBP", color:"#0070F3", industry:"IT Services",  city:"Pune",       state:"Maharashtra",  employeeCount:15000, activeEmployeeCount:14200, portalId:"orbithcm",   portalName:"OrbitHCM", policyVersion:"v5.0", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:24, contractStart:"2021-01-01", contractEnd:"2026-12-31", accountManager:"Rahul Mehta",    billingCurrency:"INR", status:"active", monthlyPayroll:48000000, pendingTimesheets:124, complianceScore:97 },
  { id:"cgi", name:"Capgemini India",         code:"CGI", color:"#003189", industry:"IT Services",  city:"Chennai",    state:"Tamil Nadu",   employeeCount:8500,  activeEmployeeCount:8100,  portalId:"cloudspire", portalName:"CloudSpire",        policyVersion:"v3.8", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-01-01", contractEnd:"2027-12-31", accountManager:"Deepa Nair",     billingCurrency:"INR", status:"active", monthlyPayroll:24500000, pendingTimesheets:52, complianceScore:92 },
  { id:"cdg", name:"Cognizant Digital",       code:"CDG", color:"#003DA5", industry:"IT Services",  city:"Chennai",    state:"Tamil Nadu",   employeeCount:6800,  activeEmployeeCount:6500,  portalId:"orbithcm",   portalName:"OrbitHCM", policyVersion:"v3.5", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.25,timezone:"Asia/Kolkata", slaHours:48, contractStart:"2022-07-01", contractEnd:"2027-06-30", accountManager:"Vikram Iyer",    billingCurrency:"INR", status:"active", monthlyPayroll:21000000, pendingTimesheets:63, complianceScore:90 },
  { id:"lti", name:"L&T Infotech",            code:"LTI", color:"#009A44", industry:"IT Services",  city:"Mumbai",     state:"Maharashtra",  employeeCount:9200,  activeEmployeeCount:8900,  portalId:"cloudspire", portalName:"CloudSpire",        policyVersion:"v4.1", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2021-10-01", contractEnd:"2026-09-30", accountManager:"Anita Rao",      billingCurrency:"INR", status:"active", monthlyPayroll:28800000, pendingTimesheets:78, complianceScore:96 },
  { id:"mnd", name:"Mindtree Ltd",            code:"MND", color:"#E94F37", industry:"IT Services",  city:"Bangalore",  state:"Karnataka",    employeeCount:7800,  activeEmployeeCount:7400,  portalId:"orbithcm",   portalName:"OrbitHCM", policyVersion:"v3.9", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-04-01", contractEnd:"2027-03-31", accountManager:"Arjun Sharma",   billingCurrency:"INR", status:"active", monthlyPayroll:26000000, pendingTimesheets:71, complianceScore:93 },
  { id:"psy", name:"Persistent Systems",      code:"PSY", color:"#C4122F", industry:"IT Services",  city:"Pune",       state:"Maharashtra",  employeeCount:5100,  activeEmployeeCount:4900,  portalId:"veltrix",  portalName:"Veltrix HCM",    policyVersion:"v3.2", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-07-01", contractEnd:"2028-06-30", accountManager:"Kavya Reddy",    billingCurrency:"INR", status:"active", monthlyPayroll:17000000, pendingTimesheets:38, complianceScore:95 },
  // ─ Mid-size (1k – 5k) ──────────────────────────────────────────────────────
  { id:"tci", name:"TechCorp India",          code:"TCI", color:"#00D4A5", industry:"IT Services",  city:"Bangalore",  state:"Karnataka",    employeeCount:3200,  activeEmployeeCount:3050,  portalId:"peoplehive", portalName:"PeopleHive",            policyVersion:"v3.2", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2022-10-01", contractEnd:"2026-09-30", accountManager:"Riya Shah",      billingCurrency:"INR", status:"active", monthlyPayroll:8640000,  pendingTimesheets:23, complianceScore:88 },
  { id:"tes", name:"Tata Elxsi",              code:"TES", color:"#00358E", industry:"IT Design",    city:"Bangalore",  state:"Karnataka",    employeeCount:3400,  activeEmployeeCount:3250,  portalId:"hrloop",     portalName:"HRLoop",            policyVersion:"v2.8", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-01-01", contractEnd:"2026-12-31", accountManager:"Riya Shah",      billingCurrency:"INR", status:"active", monthlyPayroll:9800000,  pendingTimesheets:29, complianceScore:91 },
  { id:"mpc", name:"Mphasis Corp",            code:"MPC", color:"#CC0033", industry:"IT Services",  city:"Bangalore",  state:"Karnataka",    employeeCount:4200,  activeEmployeeCount:4000,  portalId:"leafhr",     portalName:"LeafHR",           policyVersion:"v2.5", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.25,timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-01-01", contractEnd:"2027-12-31", accountManager:"Deepa Nair",     billingCurrency:"INR", status:"active", monthlyPayroll:11200000, pendingTimesheets:35, complianceScore:89 },
  { id:"cyn", name:"Cyient Ltd",              code:"CYN", color:"#5B2C8D", industry:"Engineering",  city:"Hyderabad",  state:"Telangana",    employeeCount:3700,  activeEmployeeCount:3550,  portalId:"talentweave",portalName:"TalentWeave",       policyVersion:"v2.1", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-10-01", contractEnd:"2027-09-30", accountManager:"Vikram Iyer",    billingCurrency:"INR", status:"active", monthlyPayroll:10600000, pendingTimesheets:41, complianceScore:87 },
  { id:"wvl", name:"Wipro VLSI",              code:"WVL", color:"#341E8D", industry:"IT Services",  city:"Bangalore",  state:"Karnataka",    employeeCount:2100,  activeEmployeeCount:2020,  portalId:"veltrix",  portalName:"Veltrix HCM",    policyVersion:"v3.6", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2022-04-01", contractEnd:"2026-03-31", accountManager:"Anita Rao",      billingCurrency:"INR", status:"active", monthlyPayroll:6300000,  pendingTimesheets:18, complianceScore:93 },
  { id:"zns", name:"Zensar Tech",             code:"ZNS", color:"#FF5722", industry:"IT Services",  city:"Pune",       state:"Maharashtra",  employeeCount:2800,  activeEmployeeCount:2650,  portalId:"peoplehive", portalName:"PeopleHive",            policyVersion:"v2.9", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-04-01", contractEnd:"2027-03-31", accountManager:"Rahul Mehta",    billingCurrency:"INR", status:"active", monthlyPayroll:7200000,  pendingTimesheets:27, complianceScore:86 },
  { id:"brl", name:"Birlasoft Ltd",           code:"BRL", color:"#BE1622", industry:"IT Services",  city:"Noida",      state:"Uttar Pradesh",employeeCount:1650,  activeEmployeeCount:1580,  portalId:"payaxis",    portalName:"PayAxis",  policyVersion:"v2.3", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-01-01", contractEnd:"2027-12-31", accountManager:"Priya Shah",     billingCurrency:"INR", status:"active", monthlyPayroll:4800000,  pendingTimesheets:15, complianceScore:91 },
  { id:"idn", name:"Intellect Design Arena",  code:"IDN", color:"#0099CC", industry:"Fintech",      city:"Chennai",    state:"Tamil Nadu",   employeeCount:1450,  activeEmployeeCount:1390,  portalId:"leafhr",     portalName:"LeafHR",           policyVersion:"v1.8", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-04-01", contractEnd:"2027-03-31", accountManager:"Arjun Sharma",   billingCurrency:"INR", status:"active", monthlyPayroll:4600000,  pendingTimesheets:12, complianceScore:90 },
  { id:"kpt", name:"KPIT Technologies",       code:"KPT", color:"#009900", industry:"AutoTech",     city:"Pune",       state:"Maharashtra",  employeeCount:1100,  activeEmployeeCount:1060,  portalId:"hrloop",     portalName:"HRLoop",            policyVersion:"v2.0", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-07-01", contractEnd:"2027-06-30", accountManager:"Kavya Reddy",    billingCurrency:"INR", status:"active", monthlyPayroll:3700000,  pendingTimesheets:11, complianceScore:88 },
  { id:"gss", name:"GlobalStaff Solutions",   code:"GSS", color:"#8B5CF6", industry:"Staffing",     city:"Mumbai",     state:"Maharashtra",  employeeCount:1800,  activeEmployeeCount:1720,  portalId:"hrloop",     portalName:"HRLoop",            policyVersion:"v2.0", weeklyHoursLimit:45, dailyHoursLimit:9,  overtimeMultiplier:1.25,timezone:"Asia/Kolkata", slaHours:48, contractStart:"2023-04-01", contractEnd:"2027-03-31", accountManager:"Riya Shah",      billingCurrency:"INR", status:"active", monthlyPayroll:5400000,  pendingTimesheets:16, complianceScore:90 },
  { id:"hhc", name:"HCL Healthcare",          code:"HHC", color:"#0079C1", industry:"Healthcare",   city:"Gurgaon",    state:"Haryana",      employeeCount:1200,  activeEmployeeCount:1150,  portalId:"peoplehive", portalName:"PeopleHive",            policyVersion:"v1.6", weeklyHoursLimit:48, dailyHoursLimit:12, overtimeMultiplier:2.0, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-01-01", contractEnd:"2027-12-31", accountManager:"Deepa Nair",     billingCurrency:"INR", status:"active", monthlyPayroll:4100000,  pendingTimesheets:14, complianceScore:85 },
  // ─ Small (< 1k employees) ──────────────────────────────────────────────────
  { id:"ngs", name:"Newgen Software",         code:"NGS", color:"#004990", industry:"IT Products",  city:"Noida",      state:"Uttar Pradesh",employeeCount:820,   activeEmployeeCount:800,   portalId:"staffpulse", portalName:"StaffPulse",              policyVersion:"v1.5", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-04-01", contractEnd:"2027-03-31", accountManager:"Rahul Mehta",    billingCurrency:"INR", status:"active", monthlyPayroll:2500000,  pendingTimesheets:8,  complianceScore:87 },
  { id:"nit", name:"NIIT Technologies",       code:"NIT", color:"#E31837", industry:"IT Training",  city:"Noida",      state:"Uttar Pradesh",employeeCount:890,   activeEmployeeCount:860,   portalId:"staffpulse", portalName:"StaffPulse",              policyVersion:"v1.4", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-07-01", contractEnd:"2027-06-30", accountManager:"Priya Shah",     billingCurrency:"INR", status:"active", monthlyPayroll:2800000,  pendingTimesheets:9,  complianceScore:86 },
  { id:"fhl", name:"FinanceHub Ltd",          code:"FHL", color:"#F59E0B", industry:"BFSI",         city:"Mumbai",     state:"Maharashtra",  employeeCount:750,   activeEmployeeCount:730,   portalId:"humanedge",  portalName:"HumanEdge",        policyVersion:"v4.1", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:0,   timezone:"Asia/Kolkata", slaHours:48, contractStart:"2022-10-01", contractEnd:"2026-09-30", accountManager:"Riya Shah",      billingCurrency:"INR", status:"active", monthlyPayroll:2200000,  pendingTimesheets:6,  complianceScore:82 },
  { id:"mtd", name:"Mastech Digital",         code:"MTD", color:"#0A84FF", industry:"IT Staffing",  city:"Hyderabad",  state:"Telangana",    employeeCount:670,   activeEmployeeCount:650,   portalId:"humanedge",  portalName:"HumanEdge",        policyVersion:"v1.3", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2025-01-01", contractEnd:"2027-12-31", accountManager:"Vikram Iyer",    billingCurrency:"INR", status:"active", monthlyPayroll:2000000,  pendingTimesheets:7,  complianceScore:89 },
  { id:"snt", name:"Sonata Software",         code:"SNT", color:"#76B041", industry:"IT Services",  city:"Bangalore",  state:"Karnataka",    employeeCount:480,   activeEmployeeCount:468,   portalId:"staffpulse", portalName:"StaffPulse",              policyVersion:"v1.6", weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-10-01", contractEnd:"2027-09-30", accountManager:"Kavya Reddy",    billingCurrency:"INR", status:"active", monthlyPayroll:1500000,  pendingTimesheets:5,  complianceScore:92 },
  { id:"msh", name:"MedSure Health",          code:"MSH", color:"#FF6B6B", industry:"Healthcare",   city:"Hyderabad",  state:"Telangana",    employeeCount:420,   activeEmployeeCount:410,   portalId:"talentweave",portalName:"TalentWeave",       policyVersion:"v1.5", weeklyHoursLimit:48, dailyHoursLimit:12, overtimeMultiplier:2.0, timezone:"Asia/Kolkata", slaHours:48, contractStart:"2024-01-01", contractEnd:"2027-12-31", accountManager:"Anita Rao",      billingCurrency:"INR", status:"active", monthlyPayroll:1600000,  pendingTimesheets:5,  complianceScore:84 },
  { id:"ncs", name:"Nucleus Software",        code:"NCS", color:"#607D8B", industry:"BFSI",         city:"Noida",      state:"Uttar Pradesh",employeeCount:290,   activeEmployeeCount:282,   emailOnly:true, policyVersion:"v1.2",            weeklyHoursLimit:40, dailyHoursLimit:8,  overtimeMultiplier:1.5, timezone:"Asia/Kolkata", slaHours:72, contractStart:"2025-04-01", contractEnd:"2027-03-31", accountManager:"Rahul Mehta",    billingCurrency:"INR", status:"active", monthlyPayroll:920000,   pendingTimesheets:3,  complianceScore:79 },
]

// ─── Seed Employees (spread across key clients) ───────────────────────────────

export const employees: Employee[] = [
  // TCI - TechCorp India
  { id:"emp001", employeeCode:"TCI0001", name:"Rahul Sharma",    email:"rahul.sharma@techcorp.in",        clientId:"tci", role:"Senior Developer",        jobCategory:"Engineering", department:"Engineering",       city:"Bangalore",  startDate:"2024-01-15", ratePerHour:500,  employmentStatus:"active",  avatarColor:"#00D4A5", managerEmail:"mgr@techcorp.in", leaveBalance:{annual:18,sick:10,casual:6,usedAnnual:5,usedSick:2,usedCasual:1} },
  { id:"emp002", employeeCode:"TCI0002", name:"Priya Menon",     email:"priya.menon@techcorp.in",         clientId:"tci", role:"UX Designer",             jobCategory:"Design",      department:"Product & Design",  city:"Bangalore",  startDate:"2024-03-01", ratePerHour:450,  employmentStatus:"active",  avatarColor:"#8B5CF6", leaveBalance:{annual:18,sick:10,casual:6,usedAnnual:8,usedSick:3,usedCasual:2} },
  { id:"emp003", employeeCode:"TCI0003", name:"Deepa Rao",       email:"deepa.rao@techcorp.in",           clientId:"tci", role:"Project Manager",         jobCategory:"PMO",         department:"PMO",               city:"Bangalore",  startDate:"2023-02-28", ratePerHour:700,  employmentStatus:"active",  avatarColor:"#F59E0B", managerEmail:"vp@techcorp.in", leaveBalance:{annual:18,sick:10,casual:6,usedAnnual:3,usedSick:0,usedCasual:1} },
  // GSS - GlobalStaff Solutions
  { id:"emp004", employeeCode:"GSS0001", name:"Amit Verma",      email:"amit.verma@globalstaff.com",      clientId:"gss", role:"Business Analyst",        jobCategory:"Consulting",  department:"Consulting",        city:"Mumbai",     startDate:"2023-07-01", ratePerHour:600,  employmentStatus:"active",  avatarColor:"#00D4A5", managerEmail:"lead@globalstaff.com", leaveBalance:{annual:21,sick:12,casual:8,usedAnnual:12,usedSick:1,usedCasual:3} },
  { id:"emp005", employeeCode:"GSS0002", name:"Arjun Kumar",     email:"arjun.kumar@globalstaff.com",     clientId:"gss", role:"Full Stack Developer",    jobCategory:"Engineering", department:"Engineering",       city:"Mumbai",     startDate:"2024-04-15", ratePerHour:480,  employmentStatus:"active",  avatarColor:"#3B82F6", managerEmail:"lead@globalstaff.com", leaveBalance:{annual:18,sick:10,casual:6,usedAnnual:1,usedSick:0,usedCasual:0} },
  // FHL - FinanceHub Ltd
  { id:"emp006", employeeCode:"FHL0001", name:"Neha Gupta",      email:"neha.gupta@financehub.co",        clientId:"fhl", role:"Financial Analyst",       jobCategory:"Finance",     department:"Finance",           city:"Mumbai",     startDate:"2022-11-15", ratePerHour:550,  employmentStatus:"active",  avatarColor:"#F59E0B", leaveBalance:{annual:24,sick:14,casual:10,usedAnnual:18,usedSick:5,usedCasual:4} },
  { id:"emp007", employeeCode:"FHL0002", name:"Sonia Das",       email:"sonia.das@financehub.co",         clientId:"fhl", role:"Senior Accountant",       jobCategory:"Finance",     department:"Finance",           city:"Mumbai",     startDate:"2021-08-01", ratePerHour:520,  employmentStatus:"notice",  avatarColor:"#EC4899", leaveBalance:{annual:24,sick:14,casual:10,usedAnnual:22,usedSick:8,usedCasual:7} },
  // MSH - MedSure Health
  { id:"emp008", employeeCode:"MSH0001", name:"Vikram Singh",    email:"vikram.singh@medsure.health",     clientId:"msh", role:"Healthcare Coordinator",  jobCategory:"Healthcare",  department:"Clinical Services", city:"Hyderabad",  startDate:"2024-06-01", ratePerHour:400,  employmentStatus:"active",  avatarColor:"#FF6B6B", leaveBalance:{annual:18,sick:15,casual:6,usedAnnual:2,usedSick:4,usedCasual:0} },
  // HEX - Hexaware Technologies
  { id:"emp009", employeeCode:"HEX0001", name:"Kavya Reddy",     email:"kavya.reddy@hexaware.com",        clientId:"hex", role:"Cloud Architect",         jobCategory:"Engineering", department:"Engineering",       city:"Mumbai",     startDate:"2022-06-01", ratePerHour:950,  employmentStatus:"active",  avatarColor:"#FF6B35", managerEmail:"director@hexaware.com", leaveBalance:{annual:21,sick:12,casual:8,usedAnnual:6,usedSick:1,usedCasual:2} },
  { id:"emp010", employeeCode:"HEX0002", name:"Suresh Nair",     email:"suresh.nair@hexaware.com",        clientId:"hex", role:"Data Scientist",          jobCategory:"Analytics",   department:"Data & Analytics",  city:"Mumbai",     startDate:"2023-03-15", ratePerHour:800,  employmentStatus:"active",  avatarColor:"#10B981", leaveBalance:{annual:21,sick:12,casual:8,usedAnnual:4,usedSick:2,usedCasual:1} },
  // IBP - Infosys BPM
  { id:"emp011", employeeCode:"IBP0001", name:"Anita Joshi",     email:"anita.joshi@infosysbpm.com",      clientId:"ibp", role:"Operations Manager",      jobCategory:"Operations",  department:"Operations",        city:"Pune",       startDate:"2021-09-01", ratePerHour:650,  employmentStatus:"active",  avatarColor:"#0070F3", managerEmail:"vp@infosysbpm.com", leaveBalance:{annual:24,sick:14,casual:10,usedAnnual:10,usedSick:3,usedCasual:4} },
  { id:"emp012", employeeCode:"IBP0002", name:"Rajesh Pillai",   email:"rajesh.pillai@infosysbpm.com",    clientId:"ibp", role:"Process Lead",            jobCategory:"Operations",  department:"Operations",        city:"Pune",       startDate:"2022-01-15", ratePerHour:580,  employmentStatus:"active",  avatarColor:"#6366F1", leaveBalance:{annual:21,sick:12,casual:8,usedAnnual:7,usedSick:1,usedCasual:2} },
  // NCS - Nucleus Software (email only)
  { id:"emp013", employeeCode:"NCS0001", name:"Mohan Tripathi",  email:"mohan.tripathi@nucleussoftware.com", clientId:"ncs", role:"Legal Analyst",       jobCategory:"Legal",       department:"Legal & Compliance",city:"Noida",      startDate:"2023-05-01", ratePerHour:700,  employmentStatus:"active",  avatarColor:"#607D8B", managerEmail:"gm@nucleussoftware.com", leaveBalance:{annual:18,sick:10,casual:6,usedAnnual:3,usedSick:1,usedCasual:0} },
  // CGI - Capgemini India
  { id:"emp014", employeeCode:"CGI0001", name:"Divya Krishnan",  email:"divya.krishnan@capgemini.com",    clientId:"cgi", role:"Principal Consultant",    jobCategory:"Consulting",  department:"Consulting",        city:"Chennai",    startDate:"2020-11-01", ratePerHour:1100, employmentStatus:"active",  avatarColor:"#003189", managerEmail:"partner@capgemini.com", leaveBalance:{annual:24,sick:14,casual:10,usedAnnual:15,usedSick:2,usedCasual:5} },
  // LTI - L&T Infotech
  { id:"emp015", employeeCode:"LTI0001", name:"Ravi Menon",      email:"ravi.menon@ltimindtree.com",      clientId:"lti", role:"Tech Lead",               jobCategory:"Engineering", department:"Engineering",       city:"Mumbai",     startDate:"2022-03-01", ratePerHour:850,  employmentStatus:"active",  avatarColor:"#009A44", managerEmail:"mgr@ltimindtree.com", leaveBalance:{annual:21,sick:12,casual:8,usedAnnual:8,usedSick:2,usedCasual:3} },
]

// ─── Timesheets ───────────────────────────────────────────────────────────────

export const timesheets: Timesheet[] = [
  {
    id:"ts001", employeeId:"emp001", clientId:"tci",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-07T09:23:00Z", source:"portal", sourceDetail:"PeopleHive", portalId:"peoplehive",
    status:"flagged", totalHours:52, regularHours:40, overtimeHours:12, leaveHours:0,
    totalPayable:29000, validationScore:62, aiConfidence:44,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:2},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:2},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:3},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:3},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:8,overtimeHours:2},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (regular)",result:"pass",detail:"40 regular hours — within limit",autoChecked:true},
      {id:"v2",category:"overtime",rule:"OT requires manager pre-approval",result:"fail",detail:"12 OT hours — no pre-approval on file",autoChecked:true},
      {id:"v3",category:"overtime",rule:"Max OT per day ≤ 3 hours (TCI policy)",result:"warning",detail:"Wed & Thu at exactly 3 hrs OT — at policy ceiling",autoChecked:true},
      {id:"v4",category:"policy",rule:"3rd consecutive week with OT > 8h",result:"warning",detail:"Pattern detected — manager review required per TCI v3.2",autoChecked:false},
      {id:"v5",category:"employment",rule:"Active employment status",result:"pass",detail:"Contract active until Dec 2026",autoChecked:true},
    ],
    flagReason:"OT pre-approval missing + 3-week consecutive OT pattern",
    flaggedBy:"ai",
  },
  {
    id:"ts002", employeeId:"emp002", clientId:"tci",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-06T14:11:00Z", source:"email",
    sourceDetail:"candidatemanager@buzzworks.com",
    emailFrom:"priya.menon@techcorp.in",
    emailSubject:"Timesheet - Week of Mar 31 - Priya Menon - TCI",
    status:"reviewing", totalHours:38, regularHours:38, overtimeHours:0, leaveHours:0,
    totalPayable:17100, validationScore:91, aiConfidence:89,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:7,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:7,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (regular)",result:"pass",detail:"38 hours — within limit",autoChecked:true},
      {id:"v2",category:"policy",rule:"Email submission: manager CC required",result:"warning",detail:"Manager mgr@techcorp.in not CC'd — noted",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Contract active",autoChecked:true},
      {id:"v4",category:"leave",rule:"No leave claimed — balance check skipped",result:"pass",detail:"No leave hours in submission",autoChecked:true},
    ],
  },
  {
    id:"ts003", employeeId:"emp004", clientId:"gss",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-07T11:05:00Z", source:"portal", sourceDetail:"HRLoop", portalId:"hrloop",
    status:"approved", totalHours:45, regularHours:45, overtimeHours:0, leaveHours:0,
    totalPayable:27000, validationScore:100, aiConfidence:97,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:9,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:9,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:9,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:9,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:9,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 45 (GSS policy)",result:"pass",detail:"45 hours — at limit, permitted",autoChecked:true},
      {id:"v2",category:"overtime",rule:"No OT claimed",result:"pass",detail:"No overtime entries",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Contract active",autoChecked:true},
      {id:"v4",category:"policy",rule:"Manager approval on portal",result:"pass",detail:"Approved by lead@globalstaff.com via portal",autoChecked:true},
    ],
    approvedBy:"Riya Shah (Ops)", approvedAt:"2026-04-08T10:00:00Z",
  },
  {
    id:"ts004", employeeId:"emp006", clientId:"fhl",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-05T08:30:00Z", source:"email",
    sourceDetail:"candidatemanager@buzzworks.com",
    emailFrom:"neha.gupta@financehub.co",
    emailSubject:"Fwd: Timesheet April Week 1 - Neha",
    status:"pending", totalHours:42, regularHours:40, overtimeHours:2, leaveHours:0,
    totalPayable:22000, validationScore:35, aiConfidence:21,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:1},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:1},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:8,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (regular)",result:"pass",detail:"40 regular hours — within limit",autoChecked:true},
      {id:"v2",category:"overtime",rule:"FHL policy: No overtime permitted",result:"fail",detail:"2 OT hours claimed — FinanceHub prohibits OT under all circumstances",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Contract active",autoChecked:true},
      {id:"v4",category:"policy",rule:"Email format: original submission required",result:"fail",detail:"Email is a forward — original not attached",autoChecked:true},
    ],
    flagReason:"OT not permitted (FHL policy v4.1) + email format non-compliant",
    flaggedBy:"system",
  },
  {
    id:"ts005", employeeId:"emp008", clientId:"msh",
    period:"Mar 31 – Apr 6, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-06",
    submittedAt:"2026-04-08T07:15:00Z", source:"portal", sourceDetail:"TalentWeave", portalId:"talentweave",
    status:"pending", totalHours:60, regularHours:48, overtimeHours:12, leaveHours:0,
    totalPayable:33600, validationScore:78, aiConfidence:73,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:12,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:12,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:0,overtimeHours:0,leaveType:"Off Day",leaveHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:12,overtimeHours:4},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:12,overtimeHours:4},
      {date:"2026-04-05",dayOfWeek:"Sat",regularHours:0,overtimeHours:4},
      {date:"2026-04-06",dayOfWeek:"Sun",regularHours:0,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 48 regular (healthcare)",result:"pass",detail:"48 regular hours — at limit",autoChecked:true},
      {id:"v2",category:"overtime",rule:"OT rate 2x for MSH employees",result:"pass",detail:"12 OT hours at ₹800/hr (2x)",autoChecked:true},
      {id:"v3",category:"policy",rule:"Minimum 1 rest day per 7-day period",result:"warning",detail:"1 rest day (Wed) — at minimum",autoChecked:true},
      {id:"v4",category:"employment",rule:"Shift schedule matches timesheet",result:"pending",detail:"Awaiting shift roster from PeopleStrong portal",autoChecked:false},
    ],
  },
  {
    id:"ts006", employeeId:"emp003", clientId:"tci",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-09T10:30:00Z", source:"email",
    sourceDetail:"candidatemanager@buzzworks.com",
    emailFrom:"deepa.rao@techcorp.in",
    emailSubject:"Timesheet Apr W1 - Deepa Rao, PM - TCI - Manager Approved",
    status:"pending", totalHours:40, regularHours:36, overtimeHours:0, leaveHours:4,
    totalPayable:25200, validationScore:88, aiConfidence:85,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:4,overtimeHours:0,leaveType:"Casual",leaveHours:4},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (regular)",result:"pass",detail:"36 work + 4 casual leave = 40 hours",autoChecked:true},
      {id:"v2",category:"leave",rule:"Casual leave balance sufficient",result:"pass",detail:"5 casual days remaining — balance ok",autoChecked:true},
      {id:"v3",category:"policy",rule:"Leave pre-approved by manager",result:"pass",detail:"Email subject confirms manager approval",autoChecked:true},
      {id:"v4",category:"employment",rule:"Active employment status",result:"pass",detail:"Contract active until Jan 2027",autoChecked:true},
    ],
  },
  {
    id:"ts007", employeeId:"emp009", clientId:"hex",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-07T12:00:00Z", source:"portal", sourceDetail:"Veltrix HCM", portalId:"veltrix",
    status:"approved", totalHours:45, regularHours:45, overtimeHours:0, leaveHours:0,
    totalPayable:42750, validationScore:100, aiConfidence:99,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:9,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:9,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:9,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:9,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:9,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 45",result:"pass",detail:"45 hours — at limit, permitted",autoChecked:true},
      {id:"v2",category:"employment",rule:"Active employment status",result:"pass",detail:"Active",autoChecked:true},
    ],
    approvedBy:"Riya Shah (Ops)", approvedAt:"2026-04-09T09:00:00Z",
  },
  {
    id:"ts008", employeeId:"emp013", clientId:"ncs",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-09T09:00:00Z", source:"email",
    sourceDetail:"candidatemanager@buzzworks.com",
    emailFrom:"mohan.tripathi@nucleussoftware.com",
    emailSubject:"Timesheet Apr W1 - Mohan Tripathi - NCS",
    status:"reviewing", totalHours:40, regularHours:40, overtimeHours:0, leaveHours:0,
    totalPayable:28000, validationScore:95, aiConfidence:92,
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:8,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (regular)",result:"pass",detail:"40 hours — within limit",autoChecked:true},
      {id:"v2",category:"policy",rule:"Email submission: no portal — accepted",result:"pass",detail:"NCS is email-only client",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Active",autoChecked:true},
    ],
  },
  // ─ Agent Mark auto-approved ────────────────────────────────────────────────
  {
    id:"ts009", employeeId:"emp010", clientId:"hex",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-07T08:10:00Z", source:"portal", sourceDetail:"Veltrix HCM", portalId:"veltrix",
    status:"approved", totalHours:40, regularHours:40, overtimeHours:0, leaveHours:0,
    totalPayable:32000, validationScore:100, aiConfidence:98,
    approvedBy:"Agent Mark", approvedAt:"2026-04-07T08:11:42Z",
    notes:"Auto-approved by Agent Mark (v2.1) — 5/5 checks passed, confidence 98%, no anomalies detected. Consistent with prior 6 weeks.",
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:8,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 45 (HEX policy)",result:"pass",detail:"40h regular — within limit",autoChecked:true},
      {id:"v2",category:"overtime",rule:"No unapproved overtime",result:"pass",detail:"0h OT logged",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Active — contract valid",autoChecked:true},
      {id:"v4",category:"leave",rule:"Leave balance sufficient",result:"pass",detail:"No leave taken this period",autoChecked:true},
      {id:"v5",category:"policy",rule:"Submission within 3-day SLA",result:"pass",detail:"Submitted Mon after period end",autoChecked:true},
    ],
  },
  {
    id:"ts010", employeeId:"emp012", clientId:"ibp",
    period:"Mar 31 – Apr 4, 2026", periodStart:"2026-03-31", periodEnd:"2026-04-04",
    submittedAt:"2026-04-07T09:00:00Z", source:"portal", sourceDetail:"OrbitHCM", portalId:"orbithcm",
    status:"approved", totalHours:40, regularHours:40, overtimeHours:0, leaveHours:0,
    totalPayable:23200, validationScore:100, aiConfidence:99,
    approvedBy:"Agent Mark", approvedAt:"2026-04-07T09:01:18Z",
    notes:"Auto-approved by Agent Mark (v2.1) — perfect match across all 5 policy checks. Employee has 100% on-time submission record (18 consecutive weeks).",
    dailyEntries:[
      {date:"2026-03-31",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-04-01",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-04-02",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-04-03",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-04-04",dayOfWeek:"Fri",regularHours:8,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (IBP policy)",result:"pass",detail:"40h — exactly at standard",autoChecked:true},
      {id:"v2",category:"overtime",rule:"No unapproved overtime",result:"pass",detail:"0h OT logged",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Active — contract valid until Dec 2026",autoChecked:true},
      {id:"v4",category:"leave",rule:"Leave balance sufficient",result:"pass",detail:"No leave applied",autoChecked:true},
      {id:"v5",category:"policy",rule:"Submission within 24-hr SLA (IBP)",result:"pass",detail:"Submitted within SLA window",autoChecked:true},
    ],
  },
  {
    id:"ts011", employeeId:"emp003", clientId:"tci",
    period:"Mar 24 – Mar 28, 2026", periodStart:"2026-03-24", periodEnd:"2026-03-28",
    submittedAt:"2026-03-31T08:45:00Z", source:"portal", sourceDetail:"PeopleHive", portalId:"peoplehive",
    status:"approved", totalHours:40, regularHours:40, overtimeHours:0, leaveHours:0,
    totalPayable:28000, validationScore:100, aiConfidence:97,
    approvedBy:"Agent Mark", approvedAt:"2026-03-31T08:46:55Z",
    notes:"Auto-approved by Agent Mark (v2.1) — clean submission, all checks green. PMO-category employees historically exhibit high compliance; pattern score 97%.",
    dailyEntries:[
      {date:"2026-03-24",dayOfWeek:"Mon",regularHours:8,overtimeHours:0},
      {date:"2026-03-25",dayOfWeek:"Tue",regularHours:8,overtimeHours:0},
      {date:"2026-03-26",dayOfWeek:"Wed",regularHours:8,overtimeHours:0},
      {date:"2026-03-27",dayOfWeek:"Thu",regularHours:8,overtimeHours:0},
      {date:"2026-03-28",dayOfWeek:"Fri",regularHours:8,overtimeHours:0},
    ],
    validationChecks:[
      {id:"v1",category:"hours",rule:"Weekly hours ≤ 40 (TCI policy)",result:"pass",detail:"40h regular — within cap",autoChecked:true},
      {id:"v2",category:"overtime",rule:"OT pre-approval mandatory",result:"pass",detail:"No OT claimed",autoChecked:true},
      {id:"v3",category:"employment",rule:"Active employment status",result:"pass",detail:"Active contract",autoChecked:true},
      {id:"v4",category:"leave",rule:"No leave balance deficit",result:"pass",detail:"Leave balance healthy",autoChecked:true},
      {id:"v5",category:"policy",rule:"Submission within 3-day SLA",result:"pass",detail:"On-time submission",autoChecked:true},
    ],
  },
]

// ─── Policy Rules (per client sample) ────────────────────────────────────────

export const policyRules: PolicyRule[] = [
  // TCI rules
  { id:"pol001", clientId:"tci", category:"hours",      name:"Standard Weekly Hours Cap",           description:"No employee may log more than 40 regular hours in a single work week.",                                          triggerCondition:"regularHours > 40",                             actionOnTrigger:"Flag timesheet for ops review",         severity:"warning",   enabled:true,  createdAt:"2023-01-01", updatedAt:"2024-06-15", createdBy:"system", aiGenerated:false, appliedCount:156, triggerCount:8 },
  { id:"pol002", clientId:"tci", category:"overtime",   name:"OT Pre-Approval Mandatory",           description:"Any overtime hours must have explicit pre-approval from the reporting manager before the work period begins.",    triggerCondition:"overtimeHours > 0 && !managerApproval",         actionOnTrigger:"Reject — request manager approval",     severity:"violation", enabled:true,  createdAt:"2023-01-01", updatedAt:"2025-01-10", createdBy:"system", aiGenerated:false, appliedCount:42,  triggerCount:15 },
  { id:"pol003", clientId:"tci", category:"overtime",   name:"Daily OT Cap (3 Hours)",               description:"Overtime on any single day cannot exceed 3 hours as per TCI policy v3.2.",                                      triggerCondition:"dailyOT > 3",                                   actionOnTrigger:"Flag for review — OT ceiling hit",      severity:"warning",   enabled:true,  createdAt:"2023-06-01", updatedAt:"2024-06-15", createdBy:"ops",    aiGenerated:false, appliedCount:28,  triggerCount:6 },
  { id:"pol004", clientId:"tci", category:"compliance", name:"Consecutive OT Pattern Alert",         description:"After 2 consecutive weeks of more than 8 overtime hours, manager review is mandatory.",                         triggerCondition:"consecutiveOTWeeks >= 2 && weeklyOT > 8",       actionOnTrigger:"Escalate to manager + ops team",        severity:"warning",   enabled:true,  createdAt:"2024-01-15", updatedAt:"2024-01-15", createdBy:"ai",     aiGenerated:true,  appliedCount:12,  triggerCount:4 },
  { id:"pol005", clientId:"tci", category:"leave",      name:"Sandwich Leave Detection",             description:"Leave taken immediately before or after a public holiday without manager approval is flagged as sandwich leave.", triggerCondition:"leaveAdjacentToHoliday && !managerApproval",    actionOnTrigger:"Flag and request manager confirmation", severity:"warning",   enabled:true,  createdAt:"2024-03-01", updatedAt:"2024-03-01", createdBy:"ai",     aiGenerated:true,  appliedCount:18,  triggerCount:5 },
  // FHL rules
  { id:"pol006", clientId:"fhl", category:"overtime",   name:"Zero Overtime Policy",                 description:"FinanceHub Ltd does not permit overtime under any circumstances. Any overtime claim will be rejected.",           triggerCondition:"overtimeHours > 0",                             actionOnTrigger:"Auto-reject — no OT permitted",         severity:"violation", enabled:true,  createdAt:"2022-10-01", updatedAt:"2022-10-01", createdBy:"system", aiGenerated:false, appliedCount:34,  triggerCount:12 },
  { id:"pol007", clientId:"fhl", category:"hours",      name:"Standard 40-Hour Week",               description:"All employees must maintain exactly 40 hours per week. Under or over submissions require explanation.",           triggerCondition:"totalHours < 38 || totalHours > 40",            actionOnTrigger:"Request explanation from employee",     severity:"warning",   enabled:true,  createdAt:"2022-10-01", updatedAt:"2024-08-20", createdBy:"system", aiGenerated:false, appliedCount:67,  triggerCount:11 },
  { id:"pol008", clientId:"fhl", category:"compliance", name:"Original Email Required",             description:"Forwarded emails are not accepted as timesheet submissions. The original employee-sent email must be attached.",  triggerCondition:"emailIsForward",                                actionOnTrigger:"Reject — request original submission",  severity:"violation", enabled:true,  createdAt:"2023-04-01", updatedAt:"2023-04-01", createdBy:"system", aiGenerated:false, appliedCount:18,  triggerCount:7 },
  // MSH rules
  { id:"pol009", clientId:"msh", category:"hours",      name:"Healthcare Shift Week Cap",            description:"Medical staff may work up to 48 regular hours per week in accordance with healthcare shift norms.",              triggerCondition:"regularHours > 48",                             actionOnTrigger:"Flag for compliance review",            severity:"violation", enabled:true,  createdAt:"2024-01-01", updatedAt:"2024-01-01", createdBy:"system", aiGenerated:false, appliedCount:45,  triggerCount:3 },
  { id:"pol010", clientId:"msh", category:"attendance", name:"Minimum 1 Rest Day Per Week",          description:"Every employee must have at least one designated rest day in each 7-day period for health and safety compliance.", triggerCondition:"restDaysInWeek < 1",                            actionOnTrigger:"Warning — contact employee and manager", severity:"warning",   enabled:true,  createdAt:"2024-01-01", updatedAt:"2024-01-01", createdBy:"system", aiGenerated:false, appliedCount:60,  triggerCount:8 },
  { id:"pol011", clientId:"msh", category:"overtime",   name:"Double-Pay for OT",                   description:"All overtime is compensated at 2× the standard hourly rate per MSH healthcare worker agreements.",               triggerCondition:"overtimeHours > 0",                             actionOnTrigger:"Auto-calculate 2x OT in payroll",       severity:"info",      enabled:true,  createdAt:"2024-01-01", updatedAt:"2024-01-01", createdBy:"system", aiGenerated:false, appliedCount:80,  triggerCount:30 },
  // GSS rules
  { id:"pol012", clientId:"gss", category:"hours",      name:"45-Hour Weekly Standard",              description:"GSS employees work a 45-hour standard week (9 hrs × 5 days). Submissions within ±2 hours auto-approve.",        triggerCondition:"regularHours > 45 || regularHours < 43",       actionOnTrigger:"Flag for review",                       severity:"warning",   enabled:true,  createdAt:"2023-04-01", updatedAt:"2024-09-01", createdBy:"system", aiGenerated:false, appliedCount:90,  triggerCount:7 },
  { id:"pol013", clientId:"gss", category:"leave",      name:"Manager CC on Email Submissions",     description:"All email timesheet submissions must CC the reporting manager. Submissions without manager CC are flagged.",       triggerCondition:"emailSubmission && !managerCC",                 actionOnTrigger:"Warning — notify and log",              severity:"warning",   enabled:true,  createdAt:"2023-06-15", updatedAt:"2023-06-15", createdBy:"system", aiGenerated:false, appliedCount:35,  triggerCount:4 },
  // HEX rules
  { id:"pol014", clientId:"hex", category:"hours",      name:"45-Hour Standard Week",               description:"Hexaware standard work week is 45 hours. Submissions up to 45 regular hours auto-approve.",                      triggerCondition:"regularHours > 45",                             actionOnTrigger:"Flag for overtime review",              severity:"warning",   enabled:true,  createdAt:"2022-04-01", updatedAt:"2024-01-01", createdBy:"system", aiGenerated:false, appliedCount:420, triggerCount:22 },
  { id:"pol015", clientId:"hex", category:"compliance", name:"Monthly Hour Target (180h)",          description:"Employees are expected to complete approximately 180 regular hours per month. Significant deviation triggers review.",triggerCondition:"monthlyRegularHours < 160 || monthlyRegularHours > 200", actionOnTrigger:"Flag for manager review",      severity:"warning",   enabled:true,  createdAt:"2022-04-01", updatedAt:"2024-01-01", createdBy:"ai",     aiGenerated:true,  appliedCount:200, triggerCount:15 },
]

// ─── AI Insights ──────────────────────────────────────────────────────────────

export const aiInsights: AIInsight[] = [
  { id:"ai001", type:"anomaly",    title:"3-Week OT Pattern — Rahul Sharma (TCI)",            description:"Rahul logged 10+ OT hours for 3 consecutive weeks. TCI policy v3.2 mandates manager review. Pre-approval missing.",  timesheetIds:["ts001"], employeeIds:["emp001"], clientId:"tci",  priority:"high",   timestamp:"2026-04-09T08:00:00Z", isRead:false, suggestedAction:"Request manager approval email from mgr@techcorp.in before processing." },
  { id:"ai002", type:"warning",    title:"OT Policy Violation — Neha Gupta (FHL)",             description:"Neha claims 2 OT hours. FinanceHub prohibits overtime under policy v4.1. Will be rejected unless corrected.",           timesheetIds:["ts004"], employeeIds:["emp006"], clientId:"fhl",  priority:"high",   timestamp:"2026-04-09T08:05:00Z", isRead:false, suggestedAction:"Send rejection notice and ask employee to resubmit without OT hours." },
  { id:"ai003", type:"suggestion", title:"2 Email Timesheets Unprocessed >48h",                description:"Priya Menon and Deepa Rao submitted via email 2–3 days ago and are still pending. SLA risk: 48h turnaround.",           timesheetIds:["ts002","ts006"],                                    priority:"medium", timestamp:"2026-04-09T08:10:00Z", isRead:false, suggestedAction:"Prioritise both timesheets — they can auto-approve given 91% and 88% validation scores." },
  { id:"ai004", type:"info",       title:"Payroll Ready: GSS Apr Week 1",                     description:"2 GlobalStaff timesheets approved and verified. Total ₹46,200 ready to process.",                                         clientId:"gss",                                                    priority:"low",    timestamp:"2026-04-09T09:00:00Z", isRead:true },
  { id:"ai005", type:"anomaly",    title:"Hexaware: 18 timesheets synced, 3 parsing errors",  description:"Darwinbox sync completed at 07:45. 3 timesheets failed parsing due to missing employee codes. Manual review needed.",    clientId:"hex",                                                    priority:"medium", timestamp:"2026-04-10T07:50:00Z", isRead:false, suggestedAction:"Open Hexaware portal and cross-check employee codes HEX8821, HEX8822, HEX8901." },
  { id:"ai006", type:"warning",    title:"Sonia Das on Notice — FHL payroll hold required",   description:"Sonia Das (FHL0002) is on notice period. Per FHL policy, payroll must be reviewed by finance before release.",           timesheetIds:["ts004"], employeeIds:["emp007"], clientId:"fhl",  priority:"high",   timestamp:"2026-04-09T09:30:00Z", isRead:false, suggestedAction:"Flag FHL payroll batch for manual finance team review." },
]

// ─── Payroll Batches ──────────────────────────────────────────────────────────

export const payrollBatches: PayrollBatch[] = [
  { id:"pay001", clientId:"hex", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:42, totalTimesheets:87, totalHours:1890, regularHours:1760, overtimeHours:130, leaveHours:0,   totalAmount:7840000, regularAmount:7410000, overtimeAmount:430000, currency:"INR", status:"draft",            createdAt:"2026-04-09", onHoldCount:3 },
  { id:"pay002", clientId:"ibp", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:68, totalTimesheets:124, totalHours:2720, regularHours:2720, overtimeHours:0,   leaveHours:240, totalAmount:9580000, regularAmount:9580000, overtimeAmount:0,       currency:"INR", status:"pending_approval", createdAt:"2026-04-08", onHoldCount:0 },
  { id:"pay003", clientId:"tci", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:8,  totalTimesheets:23,  totalHours:320,  regularHours:305,  overtimeHours:15,  leaveHours:8,   totalAmount:1240000, regularAmount:1210000, overtimeAmount:30000,   currency:"INR", status:"draft",            createdAt:"2026-04-09", onHoldCount:2 },
  { id:"pay004", clientId:"gss", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:11, totalTimesheets:16,  totalHours:495,  regularHours:495,  overtimeHours:0,   leaveHours:0,   totalAmount:2020000, regularAmount:2020000, overtimeAmount:0,       currency:"INR", status:"approved",         createdAt:"2026-04-08", approvedBy:"Riya Shah", approvedAt:"2026-04-09T11:00:00Z", onHoldCount:0 },
  { id:"pay005", clientId:"fhl", period:"Mar 2026",            periodStart:"2026-03-01", periodEnd:"2026-03-31", approvedTimesheets:29, totalTimesheets:29,  totalHours:1160, regularHours:1160, overtimeHours:0,   leaveHours:80,  totalAmount:4200000, regularAmount:4200000, overtimeAmount:0,       currency:"INR", status:"processed",        createdAt:"2026-04-01", approvedBy:"Riya Shah", approvedAt:"2026-04-02T10:00:00Z", processedAt:"2026-04-03T14:00:00Z", onHoldCount:0 },
  { id:"pay006", clientId:"msh", period:"Mar 2026",            periodStart:"2026-03-01", periodEnd:"2026-03-31", approvedTimesheets:18, totalTimesheets:20,  totalHours:972,  regularHours:864,  overtimeHours:108, leaveHours:0,   totalAmount:680000, regularAmount:518400,   overtimeAmount:161600,  currency:"INR", status:"processed",        createdAt:"2026-04-01", approvedBy:"Riya Shah", approvedAt:"2026-04-02T12:00:00Z", processedAt:"2026-04-03T16:00:00Z", onHoldCount:0 },
  { id:"pay007", clientId:"cgi", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:35, totalTimesheets:52,  totalHours:1575, regularHours:1485, overtimeHours:90,  leaveHours:0,   totalAmount:6800000, regularAmount:6440000, overtimeAmount:360000,  currency:"INR", status:"pending_approval", createdAt:"2026-04-09", onHoldCount:1 },
  { id:"pay008", clientId:"lti", period:"Apr 2026 (Week 1)",   periodStart:"2026-03-30", periodEnd:"2026-04-04", approvedTimesheets:55, totalTimesheets:78,  totalHours:2475, regularHours:2340, overtimeHours:135, leaveHours:0,   totalAmount:8900000, regularAmount:8380000, overtimeAmount:520000,  currency:"INR", status:"draft",            createdAt:"2026-04-09", onHoldCount:4 },
]

// ─── Weekly Trend ─────────────────────────────────────────────────────────────

export const weeklyTrend = [
  { week:"Mar W1", received:142, processed:138, autoApproved:82 },
  { week:"Mar W2", received:168, processed:161, autoApproved:95 },
  { week:"Mar W3", received:175, processed:168, autoApproved:101 },
  { week:"Mar W4", received:151, processed:148, autoApproved:89 },
  { week:"Apr W1", received:186, processed:74,  autoApproved:44 },
]

// ─── Client Distribution (for dashboard donut) ────────────────────────────────

export const clientDistribution = [
  { name:"HEX", value:87,  color:"#FF6B35" },
  { name:"IBP", value:124, color:"#0070F3" },
  { name:"CGI", value:52,  color:"#003189" },
  { name:"LTI", value:78,  color:"#009A44" },
  { name:"Others", value:295, color:"rgba(255,255,255,0.15)" },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getEmployee(id: string) { return employees.find(e => e.id === id) }
export function getClient(id: string)   { return clients.find(c => c.id === id) }
export function getPortal(id: string)   { return portals.find(p => p.id === id) }

export function getClientPolicyRules(clientId: string) {
  return policyRules.filter(r => r.clientId === clientId)
}

export function getClientPayrollBatches(clientId: string) {
  return payrollBatches.filter(b => b.clientId === clientId)
}

// Legacy alias — keeps existing pages compiling
export const payrollSummaries: PayrollSummary[] = payrollBatches.map(b => ({
  clientId: b.clientId,
  period: b.period,
  approvedTimesheets: b.approvedTimesheets,
  totalHours: b.totalHours,
  totalAmount: b.totalAmount,
  currency: b.currency,
  status: b.status === "approved" ? "pending_approval" : b.status === "processed" ? "processed" : "draft",
}))
