import type { Client, Employee, Timesheet, AIInsight, PayrollSummary } from "./types"

export const clients: Client[] = [
  {
    id: "tci",
    name: "TechCorp India",
    code: "TCI",
    color: "#00D4A5",
    portalName: "TechCorp HRM Portal",
    policyVersion: "v3.2",
    weeklyHoursLimit: 40,
    dailyHoursLimit: 8,
    overtimeMultiplier: 1.5,
    timezone: "Asia/Kolkata",
  },
  {
    id: "gss",
    name: "GlobalStaff Solutions",
    code: "GSS",
    color: "#8B5CF6",
    portalName: "GlobalStaff HRMS",
    policyVersion: "v2.0",
    weeklyHoursLimit: 45,
    dailyHoursLimit: 9,
    overtimeMultiplier: 1.25,
    timezone: "Asia/Kolkata",
  },
  {
    id: "fhl",
    name: "FinanceHub Ltd",
    code: "FHL",
    color: "#F59E0B",
    policyVersion: "v4.1",
    weeklyHoursLimit: 40,
    dailyHoursLimit: 8,
    overtimeMultiplier: 0,
    timezone: "Asia/Kolkata",
  },
  {
    id: "msh",
    name: "MedSure Health",
    code: "MSH",
    color: "#FF6B6B",
    portalName: "MedSure Workforce",
    policyVersion: "v1.5",
    weeklyHoursLimit: 48,
    dailyHoursLimit: 12,
    overtimeMultiplier: 2.0,
    timezone: "Asia/Kolkata",
  },
]

export const employees: Employee[] = [
  {
    id: "emp001",
    name: "Rahul Sharma",
    email: "rahul.sharma@techcorp.in",
    clientId: "tci",
    role: "Senior Developer",
    department: "Engineering",
    startDate: "2024-01-15",
    ratePerHour: 500,
    leaveBalance: { annual: 18, sick: 10, casual: 6, usedAnnual: 5, usedSick: 2, usedCasual: 1 },
    managerEmail: "mgr@techcorp.in",
  },
  {
    id: "emp002",
    name: "Priya Menon",
    email: "priya.menon@techcorp.in",
    clientId: "tci",
    role: "UX Designer",
    department: "Design",
    startDate: "2024-03-01",
    ratePerHour: 450,
    leaveBalance: { annual: 18, sick: 10, casual: 6, usedAnnual: 8, usedSick: 3, usedCasual: 2 },
  },
  {
    id: "emp003",
    name: "Amit Verma",
    email: "amit.verma@globalstaff.com",
    clientId: "gss",
    role: "Business Analyst",
    department: "Consulting",
    startDate: "2023-07-01",
    ratePerHour: 600,
    leaveBalance: { annual: 21, sick: 12, casual: 8, usedAnnual: 12, usedSick: 1, usedCasual: 3 },
    managerEmail: "team.lead@globalstaff.com",
  },
  {
    id: "emp004",
    name: "Neha Gupta",
    email: "neha.gupta@financehub.co",
    clientId: "fhl",
    role: "Financial Analyst",
    department: "Finance",
    startDate: "2022-11-15",
    ratePerHour: 550,
    leaveBalance: { annual: 24, sick: 14, casual: 10, usedAnnual: 18, usedSick: 5, usedCasual: 4 },
  },
  {
    id: "emp005",
    name: "Vikram Singh",
    email: "vikram.singh@medsure.health",
    clientId: "msh",
    role: "Healthcare Coordinator",
    department: "Operations",
    startDate: "2024-06-01",
    ratePerHour: 400,
    leaveBalance: { annual: 18, sick: 15, casual: 6, usedAnnual: 2, usedSick: 4, usedCasual: 0 },
  },
  {
    id: "emp006",
    name: "Deepa Rao",
    email: "deepa.rao@techcorp.in",
    clientId: "tci",
    role: "Project Manager",
    department: "PMO",
    startDate: "2023-02-28",
    ratePerHour: 700,
    leaveBalance: { annual: 18, sick: 10, casual: 6, usedAnnual: 3, usedSick: 0, usedCasual: 1 },
    managerEmail: "vp@techcorp.in",
  },
  {
    id: "emp007",
    name: "Arjun Kumar",
    email: "arjun.kumar@globalstaff.com",
    clientId: "gss",
    role: "Full Stack Developer",
    department: "Technology",
    startDate: "2024-04-15",
    ratePerHour: 480,
    leaveBalance: { annual: 18, sick: 10, casual: 6, usedAnnual: 1, usedSick: 0, usedCasual: 0 },
    managerEmail: "team.lead@globalstaff.com",
  },
  {
    id: "emp008",
    name: "Sonia Das",
    email: "sonia.das@financehub.co",
    clientId: "fhl",
    role: "Senior Accountant",
    department: "Finance",
    startDate: "2021-08-01",
    ratePerHour: 520,
    leaveBalance: { annual: 24, sick: 14, casual: 10, usedAnnual: 22, usedSick: 8, usedCasual: 7 },
  },
]

export const timesheets: Timesheet[] = [
  {
    id: "ts001",
    employeeId: "emp001",
    clientId: "tci",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-07T09:23:00Z",
    source: "portal",
    sourceDetail: "TechCorp HRM Portal",
    status: "flagged",
    totalHours: 52,
    regularHours: 40,
    overtimeHours: 12,
    leaveHours: 0,
    totalPayable: 29000,
    validationScore: 62,
    aiConfidence: 44,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 2 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 2 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 8, overtimeHours: 3 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 3 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 8, overtimeHours: 2 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 40 (regular)", result: "pass", detail: "40 regular hours — within limit", autoChecked: true },
      { id: "v2", category: "overtime", rule: "OT requires manager pre-approval", result: "fail", detail: "12 OT hours — no pre-approval on file", autoChecked: true },
      { id: "v3", category: "overtime", rule: "Max OT per day ≤ 3 hours (TCI policy)", result: "warning", detail: "Wed & Thu at exactly 3 hrs OT — at policy ceiling", autoChecked: true },
      { id: "v4", category: "policy", rule: "3rd consecutive week with OT > 8h", result: "warning", detail: "Pattern detected — manager review required per TCI v3.2", autoChecked: false },
      { id: "v5", category: "employment", rule: "Active employment status", result: "pass", detail: "Contract active until Dec 2026", autoChecked: true },
    ],
    flagReason: "OT pre-approval missing + 3-week consecutive OT pattern",
    flaggedBy: "ai",
  },
  {
    id: "ts002",
    employeeId: "emp002",
    clientId: "tci",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-06T14:11:00Z",
    source: "email",
    sourceDetail: "candidatemanager@buzzworks.com",
    emailFrom: "priya.menon@techcorp.in",
    emailSubject: "Timesheet - Week of Mar 31 - Priya Menon - TCI",
    status: "reviewing",
    totalHours: 38,
    regularHours: 38,
    overtimeHours: 0,
    leaveHours: 0,
    totalPayable: 17100,
    validationScore: 91,
    aiConfidence: 89,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 7, overtimeHours: 0 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 7, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 40 (regular)", result: "pass", detail: "38 hours — within limit", autoChecked: true },
      { id: "v2", category: "policy", rule: "Email submission: manager CC required", result: "warning", detail: "Manager mgr@techcorp.in not CC'd — notify and note", autoChecked: true },
      { id: "v3", category: "employment", rule: "Active employment status", result: "pass", detail: "Contract active", autoChecked: true },
      { id: "v4", category: "leave", rule: "No leave claimed — balance check skipped", result: "pass", detail: "No leave hours in submission", autoChecked: true },
    ],
  },
  {
    id: "ts003",
    employeeId: "emp003",
    clientId: "gss",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-07T11:05:00Z",
    source: "portal",
    sourceDetail: "GlobalStaff HRMS",
    status: "approved",
    totalHours: 45,
    regularHours: 45,
    overtimeHours: 0,
    leaveHours: 0,
    totalPayable: 27000,
    validationScore: 100,
    aiConfidence: 97,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 9, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 9, overtimeHours: 0 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 9, overtimeHours: 0 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 9, overtimeHours: 0 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 9, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 45 (GSS policy)", result: "pass", detail: "45 hours — at limit, permitted", autoChecked: true },
      { id: "v2", category: "overtime", rule: "No OT claimed", result: "pass", detail: "No overtime entries", autoChecked: true },
      { id: "v3", category: "employment", rule: "Active employment status", result: "pass", detail: "Contract active", autoChecked: true },
      { id: "v4", category: "policy", rule: "Manager approval on portal", result: "pass", detail: "Approved by team.lead@globalstaff.com via portal", autoChecked: true },
    ],
    approvedBy: "Riya Shah (Ops)",
    approvedAt: "2026-04-08T10:00:00Z",
  },
  {
    id: "ts004",
    employeeId: "emp004",
    clientId: "fhl",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-05T08:30:00Z",
    source: "email",
    sourceDetail: "candidatemanager@buzzworks.com",
    emailFrom: "neha.gupta@financehub.co",
    emailSubject: "Fwd: Timesheet April Week 1 - Neha",
    status: "pending",
    totalHours: 42,
    regularHours: 40,
    overtimeHours: 2,
    leaveHours: 0,
    totalPayable: 22000,
    validationScore: 35,
    aiConfidence: 21,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 1 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 1 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 8, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 40 (regular)", result: "pass", detail: "40 regular hours — within limit", autoChecked: true },
      { id: "v2", category: "overtime", rule: "FHL policy: No overtime permitted", result: "fail", detail: "2 OT hours claimed — FinanceHub prohibits OT under all circumstances", autoChecked: true },
      { id: "v3", category: "employment", rule: "Active employment status", result: "pass", detail: "Contract active", autoChecked: true },
      { id: "v4", category: "policy", rule: "Email format: original submission required", result: "fail", detail: "Email is a forward — original employee submission not attached", autoChecked: true },
    ],
    flagReason: "OT not permitted (FHL policy v4.1) + email format non-compliant",
    flaggedBy: "system",
  },
  {
    id: "ts005",
    employeeId: "emp005",
    clientId: "msh",
    period: "Mar 31 – Apr 6, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-06",
    submittedAt: "2026-04-08T07:15:00Z",
    source: "portal",
    sourceDetail: "MedSure Workforce",
    status: "pending",
    totalHours: 60,
    regularHours: 48,
    overtimeHours: 12,
    leaveHours: 0,
    totalPayable: 33600,
    validationScore: 78,
    aiConfidence: 73,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 12, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 12, overtimeHours: 0 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 0, overtimeHours: 0, leaveType: "Off Day", leaveHours: 0 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 12, overtimeHours: 4 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 12, overtimeHours: 4 },
      { date: "2026-04-05", dayOfWeek: "Sat", regularHours: 0, overtimeHours: 4 },
      { date: "2026-04-06", dayOfWeek: "Sun", regularHours: 0, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 48 regular (healthcare)", result: "pass", detail: "48 regular hours — at limit, within healthcare allowance", autoChecked: true },
      { id: "v2", category: "overtime", rule: "OT rate 2x for MSH employees", result: "pass", detail: "12 OT hours calculated at ₹800/hr (2x)", autoChecked: true },
      { id: "v3", category: "policy", rule: "Minimum 1 rest day per 7-day period", result: "warning", detail: "1 rest day (Wed) — at minimum. Consider workload review", autoChecked: true },
      { id: "v4", category: "employment", rule: "Shift schedule matches timesheet", result: "pending", detail: "Awaiting shift roster from MedSure Workforce portal", autoChecked: false },
    ],
  },
  {
    id: "ts006",
    employeeId: "emp006",
    clientId: "tci",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-09T10:30:00Z",
    source: "email",
    sourceDetail: "candidatemanager@buzzworks.com",
    emailFrom: "deepa.rao@techcorp.in",
    emailSubject: "Timesheet Apr W1 - Deepa Rao, PM - TCI - Manager Approved",
    status: "pending",
    totalHours: 40,
    regularHours: 36,
    overtimeHours: 0,
    leaveHours: 4,
    totalPayable: 25200,
    validationScore: 88,
    aiConfidence: 85,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 4, overtimeHours: 0, leaveType: "Casual", leaveHours: 4 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 40 (regular)", result: "pass", detail: "36 work + 4 casual leave = 40 hours", autoChecked: true },
      { id: "v2", category: "leave", rule: "Casual leave balance sufficient", result: "pass", detail: "5 casual days remaining, 0.5 day used — balance: 4.5 days", autoChecked: true },
      { id: "v3", category: "policy", rule: "Leave pre-approved by manager", result: "pass", detail: "Email subject confirms manager approval for Fri half-day", autoChecked: true },
      { id: "v4", category: "employment", rule: "Active employment status", result: "pass", detail: "Contract active until Jan 2027", autoChecked: true },
    ],
  },
  {
    id: "ts007",
    employeeId: "emp007",
    clientId: "gss",
    period: "Mar 24 – Mar 28, 2026",
    periodStart: "2026-03-24",
    periodEnd: "2026-03-28",
    submittedAt: "2026-03-31T16:00:00Z",
    source: "portal",
    sourceDetail: "GlobalStaff HRMS",
    status: "processed",
    totalHours: 40,
    regularHours: 40,
    overtimeHours: 0,
    leaveHours: 0,
    totalPayable: 19200,
    validationScore: 100,
    aiConfidence: 98,
    dailyEntries: [
      { date: "2026-03-24", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 0 },
      { date: "2026-03-25", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 0 },
      { date: "2026-03-26", dayOfWeek: "Wed", regularHours: 8, overtimeHours: 0 },
      { date: "2026-03-27", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 0 },
      { date: "2026-03-28", dayOfWeek: "Fri", regularHours: 8, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 45", result: "pass", detail: "40 hours", autoChecked: true },
      { id: "v2", category: "employment", rule: "Active employment status", result: "pass", detail: "Active", autoChecked: true },
    ],
    approvedBy: "Riya Shah (Ops)",
    approvedAt: "2026-04-02T09:00:00Z",
  },
  {
    id: "ts008",
    employeeId: "emp008",
    clientId: "fhl",
    period: "Mar 31 – Apr 4, 2026",
    periodStart: "2026-03-31",
    periodEnd: "2026-04-04",
    submittedAt: "2026-04-07T13:45:00Z",
    source: "manual",
    status: "reviewing",
    totalHours: 32,
    regularHours: 32,
    overtimeHours: 0,
    leaveHours: 8,
    totalPayable: 16640,
    validationScore: 79,
    aiConfidence: 76,
    dailyEntries: [
      { date: "2026-03-31", dayOfWeek: "Mon", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-01", dayOfWeek: "Tue", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-02", dayOfWeek: "Wed", regularHours: 0, overtimeHours: 0, leaveType: "Sick", leaveHours: 8 },
      { date: "2026-04-03", dayOfWeek: "Thu", regularHours: 8, overtimeHours: 0 },
      { date: "2026-04-04", dayOfWeek: "Fri", regularHours: 8, overtimeHours: 0 },
    ],
    validationChecks: [
      { id: "v1", category: "hours", rule: "Weekly hours ≤ 40 (regular)", result: "pass", detail: "32 work + 8 sick leave — within policy", autoChecked: true },
      { id: "v2", category: "leave", rule: "Sick leave balance sufficient", result: "warning", detail: "Only 6 sick hours remaining after this claim — nearly exhausted", autoChecked: true },
      { id: "v3", category: "leave", rule: "Medical certificate required for sick leave > 1 day", result: "pending", detail: "1 day sick leave claimed — certificate not yet received", autoChecked: false },
      { id: "v4", category: "employment", rule: "Active employment status", result: "pass", detail: "Active", autoChecked: true },
    ],
  },
]

export const aiInsights: AIInsight[] = [
  {
    id: "ai001",
    type: "anomaly",
    title: "3-Week OT Pattern — Rahul Sharma (TCI)",
    description: "Rahul logged 10+ OT hours for 3 consecutive weeks. TCI policy v3.2 mandates manager review after 2 consecutive OT weeks. Pre-approval is missing from current timesheet.",
    timesheetIds: ["ts001"],
    employeeIds: ["emp001"],
    clientId: "tci",
    priority: "high",
    timestamp: "2026-04-09T08:00:00Z",
    isRead: false,
  },
  {
    id: "ai002",
    type: "warning",
    title: "OT Policy Violation — Neha Gupta (FHL)",
    description: "Neha's timesheet claims 2 OT hours. FinanceHub Ltd prohibits overtime under policy v4.1. This timesheet will be rejected unless OT hours are removed.",
    timesheetIds: ["ts004"],
    employeeIds: ["emp004"],
    clientId: "fhl",
    priority: "high",
    timestamp: "2026-04-09T08:05:00Z",
    isRead: false,
  },
  {
    id: "ai003",
    type: "suggestion",
    title: "2 Email Timesheets Unprocessed >48h",
    description: "Priya Menon and Deepa Rao submitted via email 2–3 days ago and are still pending. SLA risk: Buzzworks commits to 48h turnaround.",
    timesheetIds: ["ts002", "ts006"],
    priority: "medium",
    timestamp: "2026-04-09T08:10:00Z",
    isRead: false,
  },
  {
    id: "ai004",
    type: "info",
    title: "Payroll Ready: GSS Apr Week 1",
    description: "2 GlobalStaff timesheets approved and verified. Total payroll of ₹46,200 ready to process for GSS Apr Week 1.",
    clientId: "gss",
    priority: "low",
    timestamp: "2026-04-09T09:00:00Z",
    isRead: true,
  },
]

export const payrollSummaries: PayrollSummary[] = [
  { clientId: "tci", period: "Mar Week 4", approvedTimesheets: 3, totalHours: 118, totalAmount: 62400, currency: "INR", status: "processed" },
  { clientId: "gss", period: "Apr Week 1", approvedTimesheets: 2, totalHours: 85, totalAmount: 46200, currency: "INR", status: "pending_approval" },
  { clientId: "fhl", period: "Mar Week 4", approvedTimesheets: 2, totalHours: 80, totalAmount: 41600, currency: "INR", status: "processed" },
  { clientId: "msh", period: "Mar Week 4", approvedTimesheets: 1, totalHours: 55, totalAmount: 22000, currency: "INR", status: "draft" },
]

export function getEmployee(id: string) {
  return employees.find((e) => e.id === id)
}

export function getClient(id: string) {
  return clients.find((c) => c.id === id)
}

export const weeklyTrend = [
  { week: "Mar W1", received: 32, processed: 30 },
  { week: "Mar W2", received: 38, processed: 35 },
  { week: "Mar W3", received: 42, processed: 38 },
  { week: "Mar W4", received: 35, processed: 33 },
  { week: "Apr W1", received: 45, processed: 20 },
]

export const clientDistribution = [
  { name: "TCI", value: 3, color: "#00D4A5" },
  { name: "GSS", value: 2, color: "#8B5CF6" },
  { name: "FHL", value: 2, color: "#F59E0B" },
  { name: "MSH", value: 1, color: "#FF6B6B" },
]
